--- 
title: "ggplot-Aufgabe" 
author: "Dirk Seidensticker" 
date: "7. Juli 2017"
fontsize: 8pt 
output: 
  beamer_presentation: 
    theme: "metropolis" 
    pandoc_args: [ 
      "--highlight-style=tango" 
    ] 
fig_caption: yes 
---

# Aufgabenstellung

## Plot

Die Verteilung der Wandungsstärken und Proportionen der gefundenen Gefäße mit Bezug auf ihre Funktion zeigt ...

&nbsp;

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(cowplot)
library(ggplot2)
library(gridExtra)

# Daten laden und mergen
finds <- read.csv("https://raw.githubusercontent.com/kacebe/AtlantGIS/master/tables/Finds.csv", sep = ',', encoding = 'UTF-8')
vessels <- read.csv("https://raw.githubusercontent.com/kacebe/AtlantGIS/master/tables/Finds_VesselTypes.csv", sep = ',', encoding = 'UTF-8')

finds <- merge(x = finds, y = vessels, by = "vesselShape")

xmax <- max(finds$wall, na.rm = TRUE)

p1 <- ggplot(finds, aes(wall, fill = vesselFunction)) + 
  geom_histogram(binwidth = 1, color = "white") + 
  scale_x_continuous(limits = c(0, xmax + (.1*xmax)), 
                     breaks = c(seq(0, (1.1*xmax), 5))) + 
  theme_classic() + 
  theme(legend.position="top", 
        legend.title=element_blank()) + 
  scale_fill_discrete(breaks = c("Vorratsgefäß", "Kultgefäß", "Symposionsgefäß"))

xmax <- max(finds$maxD, na.rm = TRUE)
ymax <- max(finds$muendungsH, na.rm = TRUE)

if (xmax < ymax) {
  max <- ymax
} else {
  max <- xmax
}

p2 <- ggplot(finds, aes(x = maxD, y = muendungsH, fill = vesselFunction)) + 
  geom_point(shape = 21, size = 4, color = "white") + 
  coord_equal() + 
  scale_x_continuous(limits = c(0, max)) + 
  scale_y_continuous(limits = c(0, max)) + 
  theme_classic() + 
  theme(legend.position="none")

legend <- get_legend(p1)

p1 <- p1 + theme(legend.position="none")

g <- grid.arrange(p1, p2, legend, ncol=2, nrow = 2, 
                  layout_matrix = rbind(c(1,2), c(3,3)),
                  widths = c(2.7, 2.7), heights = c(2, 0.9))
```

```{r, eval=FALSE}
ggsave("../output/Fig.png", g, width = 8, height = 6)
ggsave("../output/Fig.pdf", g, width = 8, height = 6)
```

## Hilfe

* merge()
* theme_...()
* mehrere ggplots in eine figure grid.arrange() (siehe http://www.sthda.com/english/wiki/ggplot2-easy-way-to-mix-multiple-graphs-on-the- same-page-r-software-and-data-visualization)

